version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VIRUS_TOTAL_API_KEY=${VIRUS_TOTAL_API_KEY}
      - VIRUSTOTAL_API_URL=${VIRUSTOTAL_API_URL}
      - WHOISXML_API_KEY=${WHOISXML_API_KEY}
      - WHOIS_API_URL=${WHOIS_API_URL}
      - MONGO_USER_NAME=${MONGO_USER_NAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - mongodb
    networks:
      - reflectiz-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - reflectiz-network

networks:
  reflectiz-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
